# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import enum
import typing

@typing.final
class AudioFrame:
    r"""
    A frame of audio data.
    """
    @property
    def buffer(self) -> builtins.bytes:
        r"""
        Raw wav data.
        """
    @property
    def rate(self) -> builtins.int:
        r"""
        The sample rate, e.g. 44100
        """
    @property
    def channels(self) -> builtins.int:
        r"""
        The number of audio channels, e.g. 2
        """
    @property
    def format(self) -> typing.Optional[AudioFormat]:
        r"""
        Use numpy to read `buffer` as this format.
        """

@typing.final
class Response:
    @property
    def visual(self) -> typing.Optional[VisualFrame]:
        r"""
        The visual frame.
        If None, the visual frame didn't update.
        """
    @property
    def audio(self) -> typing.Optional[AudioFrame]:
        r"""
        The audio frame.
        If None, the audio frame either didn't update or there is no audio.
        """
    @property
    def sensor(self) -> typing.Optional[builtins.str]:
        r"""
        If not None, this is the ID of the sensor triggered the end of the node.
        """
    @property
    def finished(self) -> builtins.bool:
        r"""
        If true, the current node finished on this frame.
        """
    def __new__(cls, buffer: bytes) -> Response:
        r"""
        Deserialize a `Response`.
        """

@typing.final
class Vector2:
    r"""
    An (x, y) vector.
    """
    ...

@typing.final
class VisualFrame:
    r"""
    A raw bitmap `buffer` and its dimensions.
    """
    @property
    def buffer(self) -> builtins.bytes:
        r"""
        A raw RGB24 bitmap.
        """
    @property
    def width(self) -> builtins.int:
        r"""
        The width of the image.
        """
    @property
    def height(self) -> builtins.int:
        r"""
        The height of the image.
        """
    def save(self, path: builtins.str) -> None:
        r"""
        Write the visual frame to disk at `path` as a .png file.
        """

@typing.final
class AudioFormat(enum.Enum):
    r"""
    The format of the samples in `AudioFrame.buffer`.
    """
    U8 = ...
    I16 = ...
    I32 = ...
    I64 = ...
    F32 = ...
    F64 = ...

def graph(graph: typing.Any) -> bytes:
    r"""
    Returns a serialized `graph`, which must be of type `nk.Graph`.
    """

def key_press(key: str) -> bytes:
    r"""
    Returns a serialized tick with a key press action.
    """

def mouse(delta: typing.Optional[Vector2], clicked: builtins.bool) -> bytes:
    r"""
    Returns a serialized mouse action.
    
    `delta` is the delta of the mouse position. If None, the mouse didn't move.
    The coordinates of `delta` must be between -0.5 and 0.5.
    This function *doesn't* attempt to clamp `delta` to realistic values.
    
    If `clicked` is true, there was a mouse click on this frame.
    """

def noop() -> bytes:
    r"""
    Returns a serialized no-op action.
    """

