// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use crate::text::*;
use crate::asset::*;
use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_CARD_TYPE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_CARD_TYPE: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_CARD_TYPE: [CardType; 3] = [
  CardType::NONE,
  CardType::Asset,
  CardType::Text,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct CardType(pub u8);
#[allow(non_upper_case_globals)]
impl CardType {
  pub const NONE: Self = Self(0);
  pub const Asset: Self = Self(1);
  pub const Text: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::Asset,
    Self::Text,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::Asset => Some("Asset"),
      Self::Text => Some("Text"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for CardType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for CardType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for CardType {
    type Output = CardType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<u8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for CardType {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for CardType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for CardType {}
pub struct CardTypeUnionTableOffset {}

pub enum CardOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Card<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Card<'a> {
  type Inner = Card<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Card<'a> {
  pub const VT_X: flatbuffers::VOffsetT = 4;
  pub const VT_Y: flatbuffers::VOffsetT = 6;
  pub const VT_W: flatbuffers::VOffsetT = 8;
  pub const VT_H: flatbuffers::VOffsetT = 10;
  pub const VT_START_MSEC: flatbuffers::VOffsetT = 12;
  pub const VT_END_MSEC: flatbuffers::VOffsetT = 14;
  pub const VT_CARD_TYPE_TYPE: flatbuffers::VOffsetT = 16;
  pub const VT_CARD_TYPE: flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Card { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CardArgs
  ) -> flatbuffers::WIPOffset<Card<'bldr>> {
    let mut builder = CardBuilder::new(_fbb);
    if let Some(x) = args.card_type { builder.add_card_type(x); }
    if let Some(x) = args.end_msec { builder.add_end_msec(x); }
    builder.add_start_msec(args.start_msec);
    builder.add_h(args.h);
    builder.add_w(args.w);
    builder.add_y(args.y);
    builder.add_x(args.x);
    builder.add_card_type_type(args.card_type_type);
    builder.finish()
  }


  #[inline]
  pub fn x(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Card::VT_X, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn y(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Card::VT_Y, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn w(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Card::VT_W, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn h(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Card::VT_H, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn start_msec(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Card::VT_START_MSEC, Some(0)).unwrap()}
  }
  #[inline]
  pub fn end_msec(&self) -> Option<i32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Card::VT_END_MSEC, None)}
  }
  #[inline]
  pub fn card_type_type(&self) -> CardType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<CardType>(Card::VT_CARD_TYPE_TYPE, Some(CardType::NONE)).unwrap()}
  }
  #[inline]
  pub fn card_type(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(Card::VT_CARD_TYPE, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn card_type_as_asset(&self) -> Option<Asset<'a>> {
    if self.card_type_type() == CardType::Asset {
      self.card_type().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Asset::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn card_type_as_text(&self) -> Option<Text<'a>> {
    if self.card_type_type() == CardType::Text {
      self.card_type().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Text::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for Card<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<f32>("x", Self::VT_X, false)?
     .visit_field::<f32>("y", Self::VT_Y, false)?
     .visit_field::<f32>("w", Self::VT_W, false)?
     .visit_field::<f32>("h", Self::VT_H, false)?
     .visit_field::<i32>("start_msec", Self::VT_START_MSEC, false)?
     .visit_field::<i32>("end_msec", Self::VT_END_MSEC, false)?
     .visit_union::<CardType, _>("card_type_type", Self::VT_CARD_TYPE_TYPE, "card_type", Self::VT_CARD_TYPE, false, |key, v, pos| {
        match key {
          CardType::Asset => v.verify_union_variant::<flatbuffers::ForwardsUOffset<Asset>>("CardType::Asset", pos),
          CardType::Text => v.verify_union_variant::<flatbuffers::ForwardsUOffset<Text>>("CardType::Text", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct CardArgs {
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
    pub start_msec: i32,
    pub end_msec: Option<i32>,
    pub card_type_type: CardType,
    pub card_type: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for CardArgs {
  #[inline]
  fn default() -> Self {
    CardArgs {
      x: 0.0,
      y: 0.0,
      w: 0.0,
      h: 0.0,
      start_msec: 0,
      end_msec: None,
      card_type_type: CardType::NONE,
      card_type: None,
    }
  }
}

pub struct CardBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CardBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_x(&mut self, x: f32) {
    self.fbb_.push_slot::<f32>(Card::VT_X, x, 0.0);
  }
  #[inline]
  pub fn add_y(&mut self, y: f32) {
    self.fbb_.push_slot::<f32>(Card::VT_Y, y, 0.0);
  }
  #[inline]
  pub fn add_w(&mut self, w: f32) {
    self.fbb_.push_slot::<f32>(Card::VT_W, w, 0.0);
  }
  #[inline]
  pub fn add_h(&mut self, h: f32) {
    self.fbb_.push_slot::<f32>(Card::VT_H, h, 0.0);
  }
  #[inline]
  pub fn add_start_msec(&mut self, start_msec: i32) {
    self.fbb_.push_slot::<i32>(Card::VT_START_MSEC, start_msec, 0);
  }
  #[inline]
  pub fn add_end_msec(&mut self, end_msec: i32) {
    self.fbb_.push_slot_always::<i32>(Card::VT_END_MSEC, end_msec);
  }
  #[inline]
  pub fn add_card_type_type(&mut self, card_type_type: CardType) {
    self.fbb_.push_slot::<CardType>(Card::VT_CARD_TYPE_TYPE, card_type_type, CardType::NONE);
  }
  #[inline]
  pub fn add_card_type(&mut self, card_type: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Card::VT_CARD_TYPE, card_type);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CardBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CardBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Card<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Card<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Card");
      ds.field("x", &self.x());
      ds.field("y", &self.y());
      ds.field("w", &self.w());
      ds.field("h", &self.h());
      ds.field("start_msec", &self.start_msec());
      ds.field("end_msec", &self.end_msec());
      ds.field("card_type_type", &self.card_type_type());
      match self.card_type_type() {
        CardType::Asset => {
          if let Some(x) = self.card_type_as_asset() {
            ds.field("card_type", &x)
          } else {
            ds.field("card_type", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        CardType::Text => {
          if let Some(x) = self.card_type_as_text() {
            ds.field("card_type", &x)
          } else {
            ds.field("card_type", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("card_type", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Card`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_card_unchecked`.
pub fn root_as_card(buf: &[u8]) -> Result<Card, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Card>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Card` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_card_unchecked`.
pub fn size_prefixed_root_as_card(buf: &[u8]) -> Result<Card, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Card>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Card` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_card_unchecked`.
pub fn root_as_card_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Card<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Card<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Card` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_card_unchecked`.
pub fn size_prefixed_root_as_card_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Card<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Card<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Card and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Card`.
pub unsafe fn root_as_card_unchecked(buf: &[u8]) -> Card {
  unsafe { flatbuffers::root_unchecked::<Card>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Card and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Card`.
pub unsafe fn size_prefixed_root_as_card_unchecked(buf: &[u8]) -> Card {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Card>(buf) }
}
#[inline]
pub fn finish_card_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Card<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_card_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Card<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
