// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use core::cmp::Ordering;
use core::mem;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum ClickOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Click<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Click<'a> {
    type Inner = Click<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> Click<'a> {
    pub const VT_X: flatbuffers::VOffsetT = 4;
    pub const VT_Y: flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Click { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args ClickArgs,
    ) -> flatbuffers::WIPOffset<Click<'bldr>> {
        let mut builder = ClickBuilder::new(_fbb);
        builder.add_y(args.y);
        builder.add_x(args.x);
        builder.finish()
    }

    #[inline]
    pub fn x(&self) -> f32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe { self._tab.get::<f32>(Click::VT_X, Some(0.0)).unwrap() }
    }
    #[inline]
    pub fn y(&self) -> f32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe { self._tab.get::<f32>(Click::VT_Y, Some(0.0)).unwrap() }
    }
}

impl flatbuffers::Verifiable for Click<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<f32>("x", Self::VT_X, false)?
            .visit_field::<f32>("y", Self::VT_Y, false)?
            .finish();
        Ok(())
    }
}
pub struct ClickArgs {
    pub x: f32,
    pub y: f32,
}
impl<'a> Default for ClickArgs {
    #[inline]
    fn default() -> Self {
        ClickArgs { x: 0.0, y: 0.0 }
    }
}

pub struct ClickBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ClickBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_x(&mut self, x: f32) {
        self.fbb_.push_slot::<f32>(Click::VT_X, x, 0.0);
    }
    #[inline]
    pub fn add_y(&mut self, y: f32) {
        self.fbb_.push_slot::<f32>(Click::VT_Y, y, 0.0);
    }
    #[inline]
    pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ClickBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        ClickBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<Click<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for Click<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("Click");
        ds.field("x", &self.x());
        ds.field("y", &self.y());
        ds.finish()
    }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Click`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_click_unchecked`.
pub fn root_as_click(buf: &[u8]) -> Result<Click, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root::<Click>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Click` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_click_unchecked`.
pub fn size_prefixed_root_as_click(buf: &[u8]) -> Result<Click, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root::<Click>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Click` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_click_unchecked`.
pub fn root_as_click_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<Click<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root_with_opts::<Click<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Click` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_click_unchecked`.
pub fn size_prefixed_root_as_click_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<Click<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root_with_opts::<Click<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Click and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Click`.
pub unsafe fn root_as_click_unchecked(buf: &[u8]) -> Click {
    unsafe { flatbuffers::root_unchecked::<Click>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Click and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Click`.
pub unsafe fn size_prefixed_root_as_click_unchecked(buf: &[u8]) -> Click {
    unsafe { flatbuffers::size_prefixed_root_unchecked::<Click>(buf) }
}
pub const CLICK_IDENTIFIER: &str = "clik";

#[inline]
pub fn click_buffer_has_identifier(buf: &[u8]) -> bool {
    flatbuffers::buffer_has_identifier(buf, CLICK_IDENTIFIER, false)
}

#[inline]
pub fn click_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
    flatbuffers::buffer_has_identifier(buf, CLICK_IDENTIFIER, true)
}

#[inline]
pub fn finish_click_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Click<'a>>,
) {
    fbb.finish(root, Some(CLICK_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_click_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Click<'a>>,
) {
    fbb.finish_size_prefixed(root, Some(CLICK_IDENTIFIER));
}
