// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum DisplayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Display<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Display<'a> {
  type Inner = Display<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Display<'a> {
  pub const VT_IMAGE: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Display { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DisplayArgs<'args>
  ) -> flatbuffers::WIPOffset<Display<'bldr>> {
    let mut builder = DisplayBuilder::new(_fbb);
    if let Some(x) = args.image { builder.add_image(x); }
    builder.finish()
  }


  #[inline]
  pub fn image(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Display::VT_IMAGE, None)}
  }
}

impl flatbuffers::Verifiable for Display<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("image", Self::VT_IMAGE, false)?
     .finish();
    Ok(())
  }
}
pub struct DisplayArgs<'a> {
    pub image: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for DisplayArgs<'a> {
  #[inline]
  fn default() -> Self {
    DisplayArgs {
      image: None,
    }
  }
}

pub struct DisplayBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> DisplayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_image(&mut self, image: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Display::VT_IMAGE, image);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> DisplayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DisplayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Display<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Display<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Display");
      ds.field("image", &self.image());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Display`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_display_unchecked`.
pub fn root_as_display(buf: &[u8]) -> Result<Display, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Display>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Display` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_display_unchecked`.
pub fn size_prefixed_root_as_display(buf: &[u8]) -> Result<Display, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Display>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Display` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_display_unchecked`.
pub fn root_as_display_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Display<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Display<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Display` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_display_unchecked`.
pub fn size_prefixed_root_as_display_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Display<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Display<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Display and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Display`.
pub unsafe fn root_as_display_unchecked(buf: &[u8]) -> Display {
  unsafe { flatbuffers::root_unchecked::<Display>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Display and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Display`.
pub unsafe fn size_prefixed_root_as_display_unchecked(buf: &[u8]) -> Display {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Display>(buf) }
}
pub const DISPLAY_IDENTIFIER: &str = "disp";

#[inline]
pub fn display_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, DISPLAY_IDENTIFIER, false)
}

#[inline]
pub fn display_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, DISPLAY_IDENTIFIER, true)
}

#[inline]
pub fn finish_display_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Display<'a>>) {
  fbb.finish(root, Some(DISPLAY_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_display_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Display<'a>>) {
  fbb.finish_size_prefixed(root, Some(DISPLAY_IDENTIFIER));
}
