// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum GraphOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Graph<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Graph<'a> {
  type Inner = Graph<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Graph<'a> {
  pub const VT_NODE_GRAPH: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Graph { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GraphArgs<'args>
  ) -> flatbuffers::WIPOffset<Graph<'bldr>> {
    let mut builder = GraphBuilder::new(_fbb);
    if let Some(x) = args.node_graph { builder.add_node_graph(x); }
    builder.finish()
  }


  #[inline]
  pub fn node_graph(&self) -> flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Graph::VT_NODE_GRAPH, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for Graph<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("node_graph", Self::VT_NODE_GRAPH, true)?
     .finish();
    Ok(())
  }
}
pub struct GraphArgs<'a> {
    pub node_graph: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for GraphArgs<'a> {
  #[inline]
  fn default() -> Self {
    GraphArgs {
      node_graph: None, // required field
    }
  }
}

pub struct GraphBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> GraphBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_node_graph(&mut self, node_graph: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Graph::VT_NODE_GRAPH, node_graph);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> GraphBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GraphBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Graph<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Graph::VT_NODE_GRAPH,"node_graph");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Graph<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Graph");
      ds.field("node_graph", &self.node_graph());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Graph`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_unchecked`.
pub fn root_as_graph(buf: &[u8]) -> Result<Graph, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Graph>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Graph` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_graph_unchecked`.
pub fn size_prefixed_root_as_graph(buf: &[u8]) -> Result<Graph, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Graph>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Graph` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_unchecked`.
pub fn root_as_graph_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Graph<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Graph<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Graph` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_unchecked`.
pub fn size_prefixed_root_as_graph_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Graph<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Graph<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Graph and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Graph`.
pub unsafe fn root_as_graph_unchecked(buf: &[u8]) -> Graph {
  unsafe { flatbuffers::root_unchecked::<Graph>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Graph and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Graph`.
pub unsafe fn size_prefixed_root_as_graph_unchecked(buf: &[u8]) -> Graph {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Graph>(buf) }
}
pub const GRAPH_IDENTIFIER: &str = "graf";

#[inline]
pub fn graph_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, GRAPH_IDENTIFIER, false)
}

#[inline]
pub fn graph_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, GRAPH_IDENTIFIER, true)
}

#[inline]
pub fn finish_graph_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Graph<'a>>) {
  fbb.finish(root, Some(GRAPH_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_graph_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Graph<'a>>) {
  fbb.finish_size_prefixed(root, Some(GRAPH_IDENTIFIER));
}
