// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use crate::effect::*;
use crate::card::*;
use crate::node::*;
use crate::sensor::*;
use crate::transition::*;
use crate::timer::*;
use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum GraphOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Graph<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Graph<'a> {
  type Inner = Graph<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Graph<'a> {
  pub const VT_START: flatbuffers::VOffsetT = 4;
  pub const VT_NODES: flatbuffers::VOffsetT = 6;
  pub const VT_TRANSITIONS: flatbuffers::VOffsetT = 8;
  pub const VT_NODEKIT_VERSION: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Graph { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GraphArgs<'args>
  ) -> flatbuffers::WIPOffset<Graph<'bldr>> {
    let mut builder = GraphBuilder::new(_fbb);
    if let Some(x) = args.nodekit_version { builder.add_nodekit_version(x); }
    if let Some(x) = args.transitions { builder.add_transitions(x); }
    if let Some(x) = args.nodes { builder.add_nodes(x); }
    if let Some(x) = args.start { builder.add_start(x); }
    builder.finish()
  }


  #[inline]
  pub fn start(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Graph::VT_START, None)}
  }
  #[inline]
  pub fn nodes(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Node<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Node>>>>(Graph::VT_NODES, None)}
  }
  #[inline]
  pub fn transitions(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Transition<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Transition>>>>(Graph::VT_TRANSITIONS, None)}
  }
  #[inline]
  pub fn nodekit_version(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Graph::VT_NODEKIT_VERSION, None)}
  }
}

impl flatbuffers::Verifiable for Graph<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("start", Self::VT_START, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Node>>>>("nodes", Self::VT_NODES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Transition>>>>("transitions", Self::VT_TRANSITIONS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("nodekit_version", Self::VT_NODEKIT_VERSION, false)?
     .finish();
    Ok(())
  }
}
pub struct GraphArgs<'a> {
    pub start: Option<flatbuffers::WIPOffset<&'a str>>,
    pub nodes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Node<'a>>>>>,
    pub transitions: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Transition<'a>>>>>,
    pub nodekit_version: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for GraphArgs<'a> {
  #[inline]
  fn default() -> Self {
    GraphArgs {
      start: None,
      nodes: None,
      transitions: None,
      nodekit_version: None,
    }
  }
}

pub struct GraphBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> GraphBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_start(&mut self, start: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Graph::VT_START, start);
  }
  #[inline]
  pub fn add_nodes(&mut self, nodes: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Node<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Graph::VT_NODES, nodes);
  }
  #[inline]
  pub fn add_transitions(&mut self, transitions: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Transition<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Graph::VT_TRANSITIONS, transitions);
  }
  #[inline]
  pub fn add_nodekit_version(&mut self, nodekit_version: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Graph::VT_NODEKIT_VERSION, nodekit_version);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> GraphBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GraphBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Graph<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Graph<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Graph");
      ds.field("start", &self.start());
      ds.field("nodes", &self.nodes());
      ds.field("transitions", &self.transitions());
      ds.field("nodekit_version", &self.nodekit_version());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Graph`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_unchecked`.
pub fn root_as_graph(buf: &[u8]) -> Result<Graph, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Graph>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Graph` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_graph_unchecked`.
pub fn size_prefixed_root_as_graph(buf: &[u8]) -> Result<Graph, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Graph>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Graph` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_unchecked`.
pub fn root_as_graph_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Graph<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Graph<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Graph` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_unchecked`.
pub fn size_prefixed_root_as_graph_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Graph<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Graph<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Graph and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Graph`.
pub unsafe fn root_as_graph_unchecked(buf: &[u8]) -> Graph {
  unsafe { flatbuffers::root_unchecked::<Graph>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Graph and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Graph`.
pub unsafe fn size_prefixed_root_as_graph_unchecked(buf: &[u8]) -> Graph {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Graph>(buf) }
}
pub const GRAPH_IDENTIFIER: &str = "graf";

#[inline]
pub fn graph_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, GRAPH_IDENTIFIER, false)
}

#[inline]
pub fn graph_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, GRAPH_IDENTIFIER, true)
}

#[inline]
pub fn finish_graph_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Graph<'a>>) {
  fbb.finish(root, Some(GRAPH_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_graph_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Graph<'a>>) {
  fbb.finish_size_prefixed(root, Some(GRAPH_IDENTIFIER));
}
