// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum KeyPressOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct KeyPress<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for KeyPress<'a> {
  type Inner = KeyPress<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> KeyPress<'a> {
  pub const VT_KEY: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    KeyPress { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args KeyPressArgs
  ) -> flatbuffers::WIPOffset<KeyPress<'bldr>> {
    let mut builder = KeyPressBuilder::new(_fbb);
    builder.add_key(args.key);
    builder.finish()
  }


  #[inline]
  pub fn key(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(KeyPress::VT_KEY, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for KeyPress<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u8>("key", Self::VT_KEY, false)?
     .finish();
    Ok(())
  }
}
pub struct KeyPressArgs {
    pub key: u8,
}
impl<'a> Default for KeyPressArgs {
  #[inline]
  fn default() -> Self {
    KeyPressArgs {
      key: 0,
    }
  }
}

pub struct KeyPressBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> KeyPressBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_key(&mut self, key: u8) {
    self.fbb_.push_slot::<u8>(KeyPress::VT_KEY, key, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> KeyPressBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    KeyPressBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<KeyPress<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for KeyPress<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("KeyPress");
      ds.field("key", &self.key());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `KeyPress`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_key_press_unchecked`.
pub fn root_as_key_press(buf: &[u8]) -> Result<KeyPress, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<KeyPress>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `KeyPress` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_key_press_unchecked`.
pub fn size_prefixed_root_as_key_press(buf: &[u8]) -> Result<KeyPress, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<KeyPress>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `KeyPress` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_key_press_unchecked`.
pub fn root_as_key_press_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<KeyPress<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<KeyPress<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `KeyPress` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_key_press_unchecked`.
pub fn size_prefixed_root_as_key_press_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<KeyPress<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<KeyPress<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a KeyPress and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `KeyPress`.
pub unsafe fn root_as_key_press_unchecked(buf: &[u8]) -> KeyPress {
  unsafe { flatbuffers::root_unchecked::<KeyPress>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed KeyPress and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `KeyPress`.
pub unsafe fn size_prefixed_root_as_key_press_unchecked(buf: &[u8]) -> KeyPress {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<KeyPress>(buf) }
}
pub const KEY_PRESS_IDENTIFIER: &str = "keyp";

#[inline]
pub fn key_press_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, KEY_PRESS_IDENTIFIER, false)
}

#[inline]
pub fn key_press_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, KEY_PRESS_IDENTIFIER, true)
}

#[inline]
pub fn finish_key_press_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<KeyPress<'a>>) {
  fbb.finish(root, Some(KEY_PRESS_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_key_press_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<KeyPress<'a>>) {
  fbb.finish_size_prefixed(root, Some(KEY_PRESS_IDENTIFIER));
}
