#![allow(clippy::all)]
#![allow(warnings)]

//! Serializable data auto-generated by the Flatbuffer schema files in `schema/`
//! Run `./fb.sh` to regenerate.
//! This file is *not* auto-generated; all other files are.

pub mod graph;
pub mod key_press;
pub mod mouse;
pub mod noop;
pub mod reset;
pub mod response;
