#![allow(clippy::all)]

//! Serializable data auto-generated by the Flatbuffer schema files in `schema/`
//! Run `./fb.sh` to regenerate.
//! This file is *not* auto-generated; all other files are.

pub mod click;
pub mod graph;
pub mod key_press;
pub mod response;
