// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

// struct Vec2, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Vec2(pub [u8; 16]);
impl Default for Vec2 { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl core::fmt::Debug for Vec2 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Vec2")
      .field("x", &self.x())
      .field("y", &self.y())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Vec2 {}
impl<'a> flatbuffers::Follow<'a> for Vec2 {
  type Inner = &'a Vec2;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a Vec2>::follow(buf, loc) }
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Vec2 {
  type Inner = &'a Vec2;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { flatbuffers::follow_cast_ref::<Vec2>(buf, loc) }
  }
}
impl<'b> flatbuffers::Push for Vec2 {
    type Output = Vec2;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const Vec2 as *const u8, <Self as flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(8)
    }
}

impl<'a> flatbuffers::Verifiable for Vec2 {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Vec2 {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    x: f64,
    y: f64,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_x(x);
    s.set_y(y);
    s
  }

  pub fn x(&self) -> f64 {
    let mut mem = core::mem::MaybeUninit::<<f64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_x(&mut self, x: f64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn y(&self) -> f64 {
    let mut mem = core::mem::MaybeUninit::<<f64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_y(&mut self, x: f64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum MouseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Mouse<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Mouse<'a> {
  type Inner = Mouse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Mouse<'a> {
  pub const VT_DELTA: flatbuffers::VOffsetT = 4;
  pub const VT_CLICKED: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Mouse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MouseArgs<'args>
  ) -> flatbuffers::WIPOffset<Mouse<'bldr>> {
    let mut builder = MouseBuilder::new(_fbb);
    if let Some(x) = args.delta { builder.add_delta(x); }
    builder.add_clicked(args.clicked);
    builder.finish()
  }


  #[inline]
  pub fn delta(&self) -> Option<&'a Vec2> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Vec2>(Mouse::VT_DELTA, None)}
  }
  #[inline]
  pub fn clicked(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Mouse::VT_CLICKED, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Mouse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<Vec2>("delta", Self::VT_DELTA, false)?
     .visit_field::<bool>("clicked", Self::VT_CLICKED, false)?
     .finish();
    Ok(())
  }
}
pub struct MouseArgs<'a> {
    pub delta: Option<&'a Vec2>,
    pub clicked: bool,
}
impl<'a> Default for MouseArgs<'a> {
  #[inline]
  fn default() -> Self {
    MouseArgs {
      delta: None,
      clicked: false,
    }
  }
}

pub struct MouseBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> MouseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_delta(&mut self, delta: &Vec2) {
    self.fbb_.push_slot_always::<&Vec2>(Mouse::VT_DELTA, delta);
  }
  #[inline]
  pub fn add_clicked(&mut self, clicked: bool) {
    self.fbb_.push_slot::<bool>(Mouse::VT_CLICKED, clicked, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> MouseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MouseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Mouse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Mouse<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Mouse");
      ds.field("delta", &self.delta());
      ds.field("clicked", &self.clicked());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Mouse`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_mouse_unchecked`.
pub fn root_as_mouse(buf: &[u8]) -> Result<Mouse, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Mouse>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Mouse` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_mouse_unchecked`.
pub fn size_prefixed_root_as_mouse(buf: &[u8]) -> Result<Mouse, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Mouse>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Mouse` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_mouse_unchecked`.
pub fn root_as_mouse_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Mouse<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Mouse<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Mouse` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_mouse_unchecked`.
pub fn size_prefixed_root_as_mouse_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Mouse<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Mouse<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Mouse and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Mouse`.
pub unsafe fn root_as_mouse_unchecked(buf: &[u8]) -> Mouse {
  unsafe { flatbuffers::root_unchecked::<Mouse>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Mouse and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Mouse`.
pub unsafe fn size_prefixed_root_as_mouse_unchecked(buf: &[u8]) -> Mouse {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Mouse>(buf) }
}
pub const MOUSE_IDENTIFIER: &str = "mous";

#[inline]
pub fn mouse_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, MOUSE_IDENTIFIER, false)
}

#[inline]
pub fn mouse_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, MOUSE_IDENTIFIER, true)
}

#[inline]
pub fn finish_mouse_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Mouse<'a>>) {
  fbb.finish(root, Some(MOUSE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_mouse_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Mouse<'a>>) {
  fbb.finish_size_prefixed(root, Some(MOUSE_IDENTIFIER));
}
