// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use core::cmp::Ordering;
use core::mem;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum NoopOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Noop<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Noop<'a> {
    type Inner = Noop<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> Noop<'a> {
    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Noop { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        _args: &'args NoopArgs,
    ) -> flatbuffers::WIPOffset<Noop<'bldr>> {
        let mut builder = NoopBuilder::new(_fbb);
        builder.finish()
    }
}

impl flatbuffers::Verifiable for Noop<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?.finish();
        Ok(())
    }
}
pub struct NoopArgs {}
impl<'a> Default for NoopArgs {
    #[inline]
    fn default() -> Self {
        NoopArgs {}
    }
}

pub struct NoopBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NoopBuilder<'a, 'b, A> {
    #[inline]
    pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NoopBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        NoopBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<Noop<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for Noop<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("Noop");
        ds.finish()
    }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Noop`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_noop_unchecked`.
pub fn root_as_noop(buf: &[u8]) -> Result<Noop, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root::<Noop>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Noop` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_noop_unchecked`.
pub fn size_prefixed_root_as_noop(buf: &[u8]) -> Result<Noop, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root::<Noop>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Noop` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_noop_unchecked`.
pub fn root_as_noop_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<Noop<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root_with_opts::<Noop<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Noop` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_noop_unchecked`.
pub fn size_prefixed_root_as_noop_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<Noop<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root_with_opts::<Noop<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Noop and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Noop`.
pub unsafe fn root_as_noop_unchecked(buf: &[u8]) -> Noop {
    unsafe { flatbuffers::root_unchecked::<Noop>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Noop and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Noop`.
pub unsafe fn size_prefixed_root_as_noop_unchecked(buf: &[u8]) -> Noop {
    unsafe { flatbuffers::size_prefixed_root_unchecked::<Noop>(buf) }
}
pub const NOOP_IDENTIFIER: &str = "noop";

#[inline]
pub fn noop_buffer_has_identifier(buf: &[u8]) -> bool {
    flatbuffers::buffer_has_identifier(buf, NOOP_IDENTIFIER, false)
}

#[inline]
pub fn noop_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
    flatbuffers::buffer_has_identifier(buf, NOOP_IDENTIFIER, true)
}

#[inline]
pub fn finish_noop_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Noop<'a>>,
) {
    fbb.finish(root, Some(NOOP_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_noop_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Noop<'a>>,
) {
    fbb.finish_size_prefixed(root, Some(NOOP_IDENTIFIER));
}
