// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum ResetOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Reset<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Reset<'a> {
  type Inner = Reset<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Reset<'a> {

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Reset { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    _args: &'args ResetArgs
  ) -> flatbuffers::WIPOffset<Reset<'bldr>> {
    let mut builder = ResetBuilder::new(_fbb);
    builder.finish()
  }

}

impl flatbuffers::Verifiable for Reset<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct ResetArgs {
}
impl<'a> Default for ResetArgs {
  #[inline]
  fn default() -> Self {
    ResetArgs {
    }
  }
}

pub struct ResetBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ResetBuilder<'a, 'b, A> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ResetBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ResetBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Reset<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Reset<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Reset");
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Reset`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_reset_unchecked`.
pub fn root_as_reset(buf: &[u8]) -> Result<Reset, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Reset>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Reset` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_reset_unchecked`.
pub fn size_prefixed_root_as_reset(buf: &[u8]) -> Result<Reset, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Reset>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Reset` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_reset_unchecked`.
pub fn root_as_reset_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Reset<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Reset<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Reset` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_reset_unchecked`.
pub fn size_prefixed_root_as_reset_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Reset<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Reset<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Reset and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Reset`.
pub unsafe fn root_as_reset_unchecked(buf: &[u8]) -> Reset {
  unsafe { flatbuffers::root_unchecked::<Reset>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Reset and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Reset`.
pub unsafe fn size_prefixed_root_as_reset_unchecked(buf: &[u8]) -> Reset {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Reset>(buf) }
}
pub const RESET_IDENTIFIER: &str = "rset";

#[inline]
pub fn reset_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, RESET_IDENTIFIER, false)
}

#[inline]
pub fn reset_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, RESET_IDENTIFIER, true)
}

#[inline]
pub fn finish_reset_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Reset<'a>>) {
  fbb.finish(root, Some(RESET_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_reset_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Reset<'a>>) {
  fbb.finish_size_prefixed(root, Some(RESET_IDENTIFIER));
}
