// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum TimerOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Timer<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Timer<'a> {
  type Inner = Timer<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Timer<'a> {
  pub const VT_START_MSEC: flatbuffers::VOffsetT = 4;
  pub const VT_END_MSEC: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Timer { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TimerArgs
  ) -> flatbuffers::WIPOffset<Timer<'bldr>> {
    let mut builder = TimerBuilder::new(_fbb);
    if let Some(x) = args.end_msec { builder.add_end_msec(x); }
    builder.add_start_msec(args.start_msec);
    builder.finish()
  }


  #[inline]
  pub fn start_msec(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Timer::VT_START_MSEC, Some(0)).unwrap()}
  }
  #[inline]
  pub fn end_msec(&self) -> Option<i32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Timer::VT_END_MSEC, None)}
  }
}

impl flatbuffers::Verifiable for Timer<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("start_msec", Self::VT_START_MSEC, false)?
     .visit_field::<i32>("end_msec", Self::VT_END_MSEC, false)?
     .finish();
    Ok(())
  }
}
pub struct TimerArgs {
    pub start_msec: i32,
    pub end_msec: Option<i32>,
}
impl<'a> Default for TimerArgs {
  #[inline]
  fn default() -> Self {
    TimerArgs {
      start_msec: 0,
      end_msec: None,
    }
  }
}

pub struct TimerBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TimerBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_start_msec(&mut self, start_msec: i32) {
    self.fbb_.push_slot::<i32>(Timer::VT_START_MSEC, start_msec, 0);
  }
  #[inline]
  pub fn add_end_msec(&mut self, end_msec: i32) {
    self.fbb_.push_slot_always::<i32>(Timer::VT_END_MSEC, end_msec);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TimerBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TimerBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Timer<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Timer<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Timer");
      ds.field("start_msec", &self.start_msec());
      ds.field("end_msec", &self.end_msec());
      ds.finish()
  }
}
