// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use core::cmp::Ordering;
use core::mem;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum TransitionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Transition<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Transition<'a> {
    type Inner = Transition<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> Transition<'a> {
    pub const VT_FROM: flatbuffers::VOffsetT = 4;
    pub const VT_SENSOR: flatbuffers::VOffsetT = 6;
    pub const VT_TO: flatbuffers::VOffsetT = 8;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Transition { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args TransitionArgs<'args>,
    ) -> flatbuffers::WIPOffset<Transition<'bldr>> {
        let mut builder = TransitionBuilder::new(_fbb);
        if let Some(x) = args.to {
            builder.add_to(x);
        }
        if let Some(x) = args.sensor {
            builder.add_sensor(x);
        }
        if let Some(x) = args.from {
            builder.add_from(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn from(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(Transition::VT_FROM, None)
        }
    }
    #[inline]
    pub fn sensor(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(Transition::VT_SENSOR, None)
        }
    }
    #[inline]
    pub fn to(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(Transition::VT_TO, None)
        }
    }
}

impl flatbuffers::Verifiable for Transition<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("from", Self::VT_FROM, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("sensor", Self::VT_SENSOR, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("to", Self::VT_TO, false)?
            .finish();
        Ok(())
    }
}
pub struct TransitionArgs<'a> {
    pub from: Option<flatbuffers::WIPOffset<&'a str>>,
    pub sensor: Option<flatbuffers::WIPOffset<&'a str>>,
    pub to: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for TransitionArgs<'a> {
    #[inline]
    fn default() -> Self {
        TransitionArgs {
            from: None,
            sensor: None,
            to: None,
        }
    }
}

pub struct TransitionBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TransitionBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_from(&mut self, from: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(Transition::VT_FROM, from);
    }
    #[inline]
    pub fn add_sensor(&mut self, sensor: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(Transition::VT_SENSOR, sensor);
    }
    #[inline]
    pub fn add_to(&mut self, to: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(Transition::VT_TO, to);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> TransitionBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        TransitionBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<Transition<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for Transition<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("Transition");
        ds.field("from", &self.from());
        ds.field("sensor", &self.sensor());
        ds.field("to", &self.to());
        ds.finish()
    }
}
