# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class Frame:
    r"""
    A frame of audio/visual data.
    """
    ...

@typing.final
class VisualFrame:
    r"""
    A raw bitmap `buffer` and its dimensions.
    """
    @property
    def buffer(self) -> builtins.list[builtins.int]:
        r"""
        A raw RGB24 bitmap.
        """
    @property
    def width(self) -> builtins.int:
        r"""
        The width of the image.
        """
    @property
    def height(self) -> builtins.int:
        r"""
        The height of the image.
        """

def render(node: typing.Any, cursor_x: builtins.float, cursor_y: builtins.float, time: builtins.int) -> Frame:
    r"""
    Given a `node`, a cursor position, and a `time` in milliseconds,
    render the audio/visual state of the node.
    """

